# ANÁLISIS Y ESTANDARIZACIÓN DE PROVEEDORES

In [1]:
import sys
import os
project_root = os.path.dirname(os.getcwd()) 
sys.path.insert(0, project_root)
from utils.imports import *

==================================================
VERSIONES DE LIBRERÍAS
==================================================
Python: 3.10.19
pandas: 2.3.3
numpy: 2.2.6
matplotlib: 3.10.0
seaborn: 0.13.2
Pandas: 2.3.3
IPython: 8.38.0

In [2]:
notebook_dir = os.path.dirname(os.path.abspath('__file__'))
data_odoo_path = os.path.join(notebook_dir, '..', 'data', 'raw', 'ProductosOdoo.csv')
df_odoo = pd.read_csv(data_odoo_path)
print(f"📦 Total productos: {len(df_odoo)}")
print(f"📋 Columnas: {list(df_odoo.columns)}")
df_odoo.head(5)

📦 Total productos: 14215
📋 Columnas: ['id', 'name', 'barcode', 'default_code', 'x_studio_many2many_field_37q_1irl4uc58', 'categ_id', 'seller_ids']

,id,name,barcode,default_code,x_studio_many2many_field_37q_1irl4uc58,categ_id,seller_ids
0,__export__.product_template_31022_88373f19,ADORNO HALLOWEN,7453066213137,CF00614/autoriza noris,NaN,Cumpleaños / Artículos de Fiesta,NaN
1,__export__.product_template_219315_4256fd8c,ARCHIVADOR VERTICAL 3 GAVETAS Y CERRADURA,NaN,NaN,NaN,All,NaN
2,__export__.product_template_219316_dfced89f,ARCHIVADOR VERTICAL 4 GAVETAS Y CERRADURA,NaN,NaN,NaN,All,NaN
3,__export__.product_template_76612_602c2239,ARTICULOS DE NAVIDAD,93,9,NaN,Navidad / Bolas,NaN
4,__export__.product_template_29991_44f2fe53,ARTICULOS FIESTA,17,1,NaN,Cumpleaños / Artículos de Fiesta,NaN

In [3]:
data_inter_path = os.path.join(notebook_dir, '..', 'data', 'raw', 'ProductosInterfuerza.xlsx')
df_int = pd.read_excel(data_inter_path)
print(f"📦 Total productos: {len(df_int)}")
print(f"📋 Columnas: {list(df_int.columns)}")
df_int.head(5)

📦 Total productos: 73681
📋 Columnas: ['Id', 'UPC Code', 'Ubicacion', 'Item Number', 'Tipo', 'Nombre', 'Proveedor Principal', 'Marca', 'Pais de Origen', 'Punto de ReOrden', 'Ultimo Precio Proveedor', 'InStock', 'Costo Promedio', 'Precio de Lista Predeterminada', 'Costo Promedio WH', 'Ultimo Precio Proveedor Purchase', 'Ultimo Costo Entrada', 'Ultimo Costo Unitario F', 'Ultimo Costo Unitario', 'Margen ', 'Creacion', 'Actualizado', 'Categoria L1', 'Categoria L2', 'Categoria L3', 'Agente', 'Status', 'Cuenta de Venta', 'Cuenta Costo', 'Cuenta de Inventario', 'Imagen', 'Comision', 'Grosor', 'Ancho', 'Altura', 'Largo', 'Impuesto', 'Lote', 'Expiracion', 'Color', 'Talla', 'Temporada', 'Prod Madre', 'Matriz Padre', 'Matriz Hijo', 'Arancel', 'Material', 'UoM InStock', 'UoM Compra', 'UoM Venta', 'Tags', 'Peso', 'Detalle']

,Id,UPC Code,Ubicacion,Item Number,Tipo,Nombre,Proveedor Principal,Marca,Pais de Origen,Punto de ReOrden,...,Matriz Padre,Matriz Hijo,Arancel,Material,UoM InStock,UoM Compra,UoM Venta,Tags,Peso,Detalle
0,PRO101109,7512155423106,BODEGA PRINCIPAL,A404/6917,PRODUCTO,GORRA FBI 7512155423106,OMER SA,GENERICO,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,SOMBRERO SHERIFF
1,PRO104891,40568000067,NaN,405686/25.95OFERTA5.00,PRODUCTO,VESTIDO LARGO DAMA CHINO,CAPI WORLDWIDE SA,ZZZZZ,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,VESTIDO LARGO DAMA CHINO
2,PRO107818,7465376497664,NaN,9599/HB2473-18,PRODUCTO,BIRRETE GRADUACION NEGRO-AZUL TELA 7465376497664,OMER SA,GENERICO,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,VIRRETE GRADUACION TELA
3,PRO107822,6930180607994,NaN,AFD-799,PRODUCTO,NUMEROS LED CHICO AFD-799,SOLARTE DE PANAMA SA,FIESTAS DAISY,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NUMEROS LED CHICO AFD-799
4,PRO107852,60000001438,BODEGA PRINCIPAL,601430,PRODUCTO,ARREGLO GRADUACION GLOBOS,CORPORACION DAISY SA,DAISY,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,ARREGLO GRADUACION GLOBOS

## ANÁLISIS DE PRODUCTOS SIN PROVEEDOR

In [15]:
df_odoo_copy = df_odoo.copy()
# Productos nulos o vacíos en seller_ids
df_null_sellers = df_odoo_copy['seller_ids'].isna()
df_empty_sellers = df_odoo_copy['seller_ids'].astype(str).str.contains(r'^\s*$', na=False)
df_without_sellers = df_null_sellers | df_empty_sellers

total_without_sellers = df_without_sellers.sum()
total_with_sellers = len(df_odoo_copy) - total_without_sellers
# Conteo de valores de la columna sellers_ids que no están vacíos
sellers = df_odoo_copy[~df_without_sellers]['seller_ids'].value_counts()

display(Markdown("#### DIAGNÓSTICO DE PROVEEDORES"))
print(f"Total productos: {len(df_odoo_copy)}")
print(f"Con proveedor: {total_with_sellers} ({total_with_sellers/len(df_odoo_copy) *100:.2f}%)")
print(f"Sin proveedor: {total_without_sellers} ({total_without_sellers/len(df_odoo_copy) *100:.2f}%)")

display(Markdown("#### ESTADÍSTICAS DE PROVEEDORES"))
print(f"Total de marcas únicas: {len(sellers)}")
print(f"Marca más frecuente: {sellers.index[0]} ({sellers.iloc[0]} productos)")
print(f"Marca menos frecuente: {sellers.index[-1]} ({sellers.iloc[-1]} productos)")

# Proveedores que aparecen solo una vez
one_seller = sellers[sellers == 1]
print(f"Proveedores con un solo producto: {len(one_seller)} ({len(one_seller)/len(sellers)*100:.2f}% del total de proveedores)")

display(Markdown("## Muestra de productos sin proveedor"))
display(df_odoo_copy[~df_without_sellers][['name','barcode','seller_ids']].head())

#### DIAGNÓSTICO DE PROVEEDORES

Total productos: 14215
Con proveedor: 8664 (60.95%)
Sin proveedor: 5551 (39.05%)

#### ESTADÍSTICAS DE PROVEEDORES

Total de marcas únicas: 222
Marca más frecuente: PROV-ARGELIA INTERNACIONAL S A (851 productos)
Marca menos frecuente: PATPHA SA (1 productos)
Proveedores con un solo producto: 47 (21.17% del total de proveedores)

## Muestra de productos sin proveedor

,name,barcode,seller_ids
5,ARTICULOS SELECTOS,9788476726662,PROV-DISTRIBUIDORA CULTURAL SA
6,BARNIZ 300CM MATE NO OLEO 10170,7707227487005,PROV-METRIC PANAMA
8,CADENA STRASS 3 LINEAS C/PIEDRA X YDA,109223,MEGA ENSAMBLES INT S.A.
10,CAJA FINELINERS KIUT PASTEL X6,7702111683921,PROV-CARVAJAL EDUCACION SA
12,CINTA GIMNASIA RITMICA cbb2394 602208,60107000075,AMAZON